#!/usr/bin/env bash
# Writes .pipemesh/affected.yaml: for each deployable service, the
# paths whose change can change it — every package in its transitive
# dependency closure, plus the files that configure Bazel itself. The
# dispatch pipeline uses these lists as `changes:` rules, so a revision
# reaches a service's pipeline only when the graph says it must.
#
#   tools/gen-rules.sh           regenerate
#   tools/gen-rules.sh --check   fail if the committed file is stale
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
bazel=tools/bazelw
out=.pipemesh/affected.yaml

gen() {
  echo "# Generated by tools/gen-rules.sh from the Bazel graph. Do not edit;"
  echo "# the dispatch pipeline's graph_is_current job fails when it is stale."
  for t in $($bazel query --noshow_progress 'attr(tags, "\bdeployable\b", //...)' 2>/dev/null); do
    svc=$(sed -E 's#^//services/([^:]+):.*#\1#' <<<"$t")
    echo "$svc:"
    for f in MODULE.bazel .bazelrc .bazelversion; do echo "  - $f"; done
    $bazel query --noshow_progress --output=package "deps($t)" 2>/dev/null \
      | grep -v '^@' | sort -u | sed 's#.*#  - &/**#'
  done
}

if [ "${1:-}" = "--check" ]; then
  if ! diff -u "$out" <(gen); then
    echo "$out is stale: run tools/gen-rules.sh and commit the result" >&2
    exit 1
  fi
  echo "$out matches the Bazel graph"
else
  gen > "$out"
  echo "wrote $out"
fi
